[build]
  command = "npm run build --verbose"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  DISABLE_ESLINT_PLUGIN = "true"
  NEXT_BUNDLE_ESLINT = "false"
  DEBUG = "*"

[[plugins]]
  package = "@netlify/plugin-nextjs" 